apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-tz-demo-app
  namespace: devops
spec:
  destination:
    namespace: devops-dev
    server: https://kubernetes.default.svc
  project: devops-dev
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: devops-tz-demo-app/dev
    repoURL: https://github.com/topzone8713/tz-argocd-repo.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
