repoServer:
  rbac:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - secrets
        - configmaps

  extraContainers:
  - command:
    - /var/run/argocd/argocd-cmp-server
    envFrom:
    - secretRef:
        name: argocd-vault-plugin-credentials
    image: registry.access.redhat.com/ubi8
    name: avp-helm
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
    volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    - mountPath: /tmp
      name: tmp
    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
      name: cmp-plugin
      subPath: avp-helm.yaml
    - mountPath: /usr/local/bin/argocd-vault-plugin
      name: custom-tools
      subPath: argocd-vault-plugin
    - mountPath: /usr/local/bin/helm
      name: custom-tools
      subPath: helm

  - command:
    - /var/run/argocd/argocd-cmp-server
    name: avp
    image: registry.access.redhat.com/ubi8
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials
    resources: {}
    volumeMounts:
      - name: var-files
        mountPath: /var/run/argocd
      - name: plugins
        mountPath: /home/argocd/cmp-server/plugins
      - name: tmp
        mountPath: /tmp
      - name: cmp-plugin
        mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: avp.yaml
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    imagePullPolicy: Always
    securityContext:
      runAsUser: 999
      runAsNonRoot: true

  initContainers:
  - args:
    - curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64
      -o argocd-vault-plugin && chmod +x argocd-vault-plugin && mv argocd-vault-plugin
      /custom-tools/ && curl -L https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz
      -o helm-v3.11.1-linux-amd64.tar.gz && tar -xvf helm-v3.11.1-linux-amd64.tar.gz
      && mv linux-amd64/helm /custom-tools/
    command:
    - sh
    - -c
    env:
    - name: AVP_VERSION
      value: 1.13.1
    image: registry.access.redhat.com/ubi8
    name: download-tools
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

  volumes:
  - configMap:
      name: cmp-plugin
    name: cmp-plugin
  - emptyDir: {}
    name: custom-tools
