apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-list
subjects:
- kind: User
  name: topzone-k8s-k8sAdmin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: topzone-k8s-k8sDev
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: doogee
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ns-list
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topzone-k8s-k8sAdmin
subjects:
- kind: Group
  name: topzone-k8s-k8sAdmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: devops-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: lens-metrics
  name: vendor-read-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-lens-metrics
subjects:
- kind: Group
  name: topzone-k8s-k8sAdmin
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: devops-admin
  apiGroup: rbac.authorization.k8s.io
