output "aws_account_id" {
  value = data.aws_caller_identity.current.account_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = local.region
}

output "s3-bucket" {
  value = aws_s3_bucket.terraform-state-eks-main.bucket
}

output "worker_groups_role" {
  description = "Outputs worker_group role"
  value       = module.eks.worker_iam_role_arn
}

output "cluster_autoscaler_role" {
  description = "Outputs cluster_autoscaler_role"
  value       = module.iam_assumable_role_admin.this_iam_role_arn
}

//output "eks-main-bastion" {
//  description = "eks-main-bastion public_ip"
//  value       = aws_instance.eks-main-bastion.public_ip
//}
//
//output "secondary-az1" {
//  description = "secondary-az1 private_ip"
//  value       = aws_instance.secondary-az1.private_ip
//}
