apiVersion: v1
data:
  loki.yaml: LOKI_ENCODE
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: loki
    app.kubernetes.io/managed-by: Helm
    release: loki
  name: loki
  namespace: monitoring
type: Opaque
