prometheusOperator:
  enabled: true
  serviceMonitor:
    selfMonitor: true
  resources:
   limits:
     cpu: 200m
     memory: 200Mi
   requests:
     cpu: 100m
     memory: 100Mi
  nodeSelector:
    environment: prod
    team: devops
#  affinity:
#    nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/e2e-az-name
#           operator: In
#           values:
#           - e2e-az1
#           - e2e-az2

prometheus:
  prometheusSpec:
    externalUrl: https://prometheus.default.eks_project.eks_domain
    nodeSelector:
      environment: prod
      team: devops
#    podAntiAffinity: ""
#    podAntiAffinityTopologyKey: kubernetes.io/hostname
#    affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#         - matchExpressions:
#           - key: kubernetes.io/e2e-az-name
#             operator: In
#             values:
#             - e2e-az1
#             - e2e-az2
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 50Gi
          storageClassName: gp2
    additionalScrapeConfigs:
      - job_name: 'tz-kubernetes-pod-job'
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        # only scrape when annotation prometheus.io/scrape: 'true' is set
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
#      - job_name: 'tz-kubernetes-service-endpoints'
#        kubernetes_sd_configs:
#        - role: endpoints
#        relabel_configs:
##          annotation:
##            prometheus.io/scrape: 'true'
##            prometheus.io/path: /metrics
##            prometheus.io/port: '9900'
##            prometheus.io/scheme: http
#        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
#          action: keep
#          regex: true
#        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
#          action: replace
#          target_label: __metrics_path__
#          regex: (.+)
#        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
#          action: replace
#          regex: ([^:]+)(?::\d+)?;(\d+)
#          replacement: $1:$2
#          target_label: __address__
#        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
#          action: replace
#          target_label: __scheme__
#          regex: (https?)
#        - action: labelmap
#          regex: __meta_kubernetes_service_label_(.+)
#        - source_labels: [__meta_kubernetes_namespace]
#          action: replace
#          target_label: kubernetes_namespace
#        - source_labels: [__meta_kubernetes_service_name]
#          action: replace
#          target_label: kubernetes_name
      - job_name: 'jenkins'
        metrics_path: /prometheus/
        static_configs:
          - targets: ['jenkins.tzcorp.com:80']
        scheme: http
        tls_config:
          insecure_skip_verify: true
        basic_auth:
          username: 'devops'
          password: 'admin_password'
      - job_name: 'tz-blackbox-exporter'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://jenkins.tzcorp.com/login
            - https://argocd.tzcorp.com
            - https://grafana.tzcorp.com
            - https://prometheus.tzcorp.com
            - https://alertmanager.default.eks_project.tzcorp.com
            - https://vault.tzcorp.com
            - https://consul.tzcorp.com
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: tz-blackbox-exporter-prometheus-blackbox-exporter:9115
      - job_name: 'prometheus'
        metrics_path: /metrics
        static_configs:
          - targets:
            # jenkins
            - 20.10.11.28:9090
            # tgdre-job
            - 10.0.1.138:9090
            # tgdre-prod
            - 10.0.2.184:9090
            - 10.0.1.212:9090
            - 10.0.1.221:9090
            # tgdkr-mrd
            - 54.180.146.14:9090
        scheme: http
      - job_name: 'node-exporter'
        scrape_interval: 5s
        static_configs:
          - targets:
            # jenkins
            - 20.10.11.28:9100
            # tgdre-job
            - 10.0.1.138:9100
            # tgdre-prod
            - 10.0.2.184:9100
            - 10.0.1.212:9100
            - 10.0.1.221:9100
            # tgdkr-mrd
            - 54.180.146.14:9100
